include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  errors:
    constant_identifier_names: "ignore"
    unnecessary_this: "ignore"
    prefer_generic_function_type_aliases: "ignore"
    avoid_renaming_method_parameters: "ignore"
    avoid_print: "ignore"
    todo: "ignore"
    body_might_complete_normally_nullable: "ignore"
    asset_does_not_exist: "error"
  exclude:
    # Files
    - "**.gr.dart"
    - "**.freezed.dart"
    - "**.cached.dart"
    - "**.g.dart"
    - "**.mocks.dart"
    - "**.config.dart"
    - "lib/generated_plugin_registrant.dart"

    # Directories
    - "build/**"
    - "assets/**"
    - "ios/**"
    - "android/**"
    - "lib/generated/**"
    - "distribution/**"

linter:
  rules:
    - always_use_package_imports
    - require_trailing_commas
    - sort_constructors_first
    - sort_pub_dependencies
