name: sportly
description: BSc thesis project

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_route: 5.0.1
  cupertino_icons: 1.0.2
  dio: 4.0.6
  easy_localization: 3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  flutter_hooks: 0.18.5+1
  flutter_launcher_icons: 0.10.0
  flutter_native_splash: 2.2.10+1
  freezed: 2.1.1
  get_it: 7.2.0
  hooked_bloc: 1.2.0
  injectable: 1.5.3

dev_dependencies: 
  build_runner: ^2.2.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
